name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  robot-automation:
    runs-on: ubuntu-latest
    container:
      image: luciano96/robot-automation:latest
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME}}
        password: ${{ secrets.DOCKER_HUB_TOKEN}}

    steps:
      - uses: actions/checkout@v3
      - name: Running automation
        run: |
          pip install -r requirements.txt
          chmod 777 ./
          robot -d ./results -v HEADLESS:True ./Cases
      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: automation-results
          path: results/
